name: Check

on:
  push:
    branches-ignore:
      - 'dependabot-**'
    paths-ignore:
      - '**.md'
  workflow_dispatch:
    branches:
      - master

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v3

    - name: Initialization
      uses: ./.github/actions/init
      with:
        jdk: 17

    - name: Build
      uses: gradle/gradle-build-action@v2.1.6
      with:
        arguments: build -x test

    - name: Test
      uses: gradle/gradle-build-action@v2.1.6
      with:
        arguments: test

    - name: Test Summary
      if: always()
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        files: "**/build/test-results/test/TEST-*.xml"