name: Check-Dependabot

on:
  pull_request_target:
    branches:
      - 'dependabot-**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: adopt

    - name: Set permission to execute gradle
      run: chmod +x gradlew

    - name: Build
      uses: gradle/gradle-build-action@v2.1.6
      with:
        arguments: build -x test

    - name: Test
      uses: gradle/gradle-build-action@v2.1.6
      with:
        arguments: test